#!/bin/bash

export CUDA_VISIBLE_DEVICES=${GPU_ID:-0}
model_name=ManiMamba

python -u scripts/run.py \
	--is_training 1 \
	--root_path ./data/ETT-small/ \
	--data_path ETTm2.csv \
	--model_id ETTm2_96_96 \
	--model $model_name \
	--data ETTm2 \
	--features M \
	--seq_len 96 \
	--pred_len 96 \
	--e_layers 3 \
	--enc_in 7 \
	--c_out 7 \
	--des 'CASESTUDY' \
	--itr 1 \
	--d_model 256 \
	--d_ff 512 \
	--d_state 8 \
	--expand 2 \
	--epsilon 1e-4 \
	--cov_window 16 \
	--cov_stride 4 \
	--cov_rank 0 \
	--geo_d_model 256 \
	--geo_d_state 8 \
	--geo_d_conv 2 \
	--geo_expand 2 \
	--batch_size 16 \
	--optim "Adam" \
	--learning_rate 7.708e-6 \
	--weight_decay 0 \
	--dropout 0.2 \
	--patience 5 \
	--warmup_epochs 3 \
	--train_epochs 15 \
	--use_amp

python -u scripts/run.py \
	--is_training 1 \
	--root_path ./data/ETT-small/ \
	--data_path ETTm2.csv \
	--model_id ETTm2_96_192 \
	--model $model_name \
	--data ETTm2 \
	--features M \
	--seq_len 96 \
	--pred_len 192 \
	--e_layers 2 \
	--enc_in 7 \
	--c_out 7 \
	--des 'CASESTUDY' \
	--itr 1 \
	--d_model 256 \
	--d_ff 512 \
	--d_state 2 \
	--expand 1 \
	--epsilon 1e-4 \
	--cov_window 32 \
	--cov_stride 16 \
	--cov_rank 0 \
	--geo_d_model 256 \
	--geo_d_state 4 \
	--geo_d_conv 4 \
	--geo_expand 1 \
	--batch_size 16 \
	--optim "Adam" \
	--learning_rate 1.349e-5 \
	--weight_decay 0 \
	--dropout 0.2 \
	--patience 5 \
	--warmup_epochs 3 \
	--train_epochs 15 \
	--use_amp

python -u scripts/run.py \
	--is_training 1 \
	--root_path ./data/ETT-small/ \
	--data_path ETTm2.csv \
	--model_id ETTm2_96_384 \
	--model $model_name \
	--data ETTm2 \
	--features M \
	--seq_len 96 \
	--pred_len 384 \
	--e_layers 3 \
	--enc_in 7 \
	--c_out 7 \
	--des 'CASESTUDY' \
	--itr 1 \
	--d_model 512 \
	--d_ff 512 \
	--d_state 8 \
	--expand 1 \
	--epsilon 1e-4 \
	--cov_window 8 \
	--cov_stride 16 \
	--cov_rank 0 \
	--geo_d_model 512 \
	--geo_d_state 16 \
	--geo_d_conv 4 \
	--geo_expand 2 \
	--batch_size 16 \
	--optim "Adam" \
	--learning_rate 5.874e-6 \
	--weight_decay 0 \
	--dropout 0.2 \
	--patience 5 \
	--warmup_epochs 3 \
	--train_epochs 15 \
	--use_amp
