PRED_LENS_BY_DATASET = {
    "ETTh1": [96, 192, 336, 720],
    "ETTh2": [96, 192, 336, 720],
    "ETTm1": [96, 192, 336, 720],
    "ETTm2": [96, 192, 336, 720],
    "Weather": [96, 192, 336, 720],
    "ECL": [96, 192, 336, 720],
    "Traffic": [96, 192, 336, 720],
    "Exchange": [96, 192, 336, 720],
    "Solar": [96, 192, 336, 720],
    "PEMS03": [12, 24, 48, 96],
    "PEMS04": [12, 24, 48, 96],
    "PEMS07": [12, 24, 48, 96],
    "PEMS08": [12, 24, 48, 96],
    "illness": [24, 36, 48, 60],
}

DATASET_CONFIGS = {
    "ETTh1": {
        "data": "ETTh1",
        "root_path": "./data/ETT-small/",
        "data_path": "ETTh1.csv",
        "enc_in": 7,
        "dec_in": 7,
        "c_out": 7,
        "freq": "h",
        "total_rows": 17420,
        "seq_len": 96,
        "label_len": 48,
    },
    "ETTh2": {
        "data": "ETTh2",
        "root_path": "./data/ETT-small/",
        "data_path": "ETTh2.csv",
        "enc_in": 7,
        "dec_in": 7,
        "c_out": 7,
        "freq": "h",
        "total_rows": 17420,
        "seq_len": 96,
        "label_len": 48,
    },
    "ETTm1": {
        "data": "ETTm1",
        "root_path": "./data/ETT-small/",
        "data_path": "ETTm1.csv",
        "enc_in": 7,
        "dec_in": 7,
        "c_out": 7,
        "freq": "t",
        "total_rows": 69680,
        "seq_len": 96,
        "label_len": 48,
    },
    "ETTm2": {
        "data": "ETTm2",
        "root_path": "./data/ETT-small/",
        "data_path": "ETTm2.csv",
        "enc_in": 7,
        "dec_in": 7,
        "c_out": 7,
        "freq": "t",
        "total_rows": 69680,
        "seq_len": 96,
        "label_len": 48,
    },
    "Weather": {
        "data": "custom",
        "root_path": "./data/weather/",
        "data_path": "weather.csv",
        "enc_in": 21,
        "dec_in": 21,
        "c_out": 21,
        "freq": "t",
        "total_rows": 52696,
        "seq_len": 96,
        "label_len": 48,
    },
    "ECL": {
        "data": "custom",
        "root_path": "./data/electricity/",
        "data_path": "electricity.csv",
        "enc_in": 321,
        "dec_in": 321,
        "c_out": 321,
        "freq": "h",
        "total_rows": 26304,
        "seq_len": 96,
        "label_len": 48,
    },
    "Traffic": {
        "data": "custom",
        "root_path": "./data/traffic/",
        "data_path": "traffic.csv",
        "enc_in": 862,
        "dec_in": 862,
        "c_out": 862,
        "freq": "h",
        "total_rows": 17544,
        "seq_len": 96,
        "label_len": 48,
    },
    "Exchange": {
        "data": "custom",
        "root_path": "./data/exchange_rate/",
        "data_path": "exchange_rate.csv",
        "enc_in": 8,
        "dec_in": 8,
        "c_out": 8,
        "freq": "d",
        "total_rows": 7588,
        "seq_len": 96,
        "label_len": 48,
    },
    "Solar": {
        "data": "Solar",
        "root_path": "./data/Solar/",
        "data_path": "solar_AL.txt",
        "enc_in": 137,
        "dec_in": 137,
        "c_out": 137,
        "freq": "h",
        "total_rows": 52560,
        "seq_len": 96,
        "label_len": 48,
    },
    "PEMS03": {
        "data": "PEMS",
        "root_path": "./data/PEMS/",
        "data_path": "PEMS03.npz",
        "enc_in": 358,
        "dec_in": 358,
        "c_out": 358,
        "freq": "h",
        "total_rows": 26208,
        "seq_len": 96,
        "label_len": 48,
    },
    "PEMS04": {
        "data": "PEMS",
        "root_path": "./data/PEMS/",
        "data_path": "PEMS04.npz",
        "enc_in": 307,
        "dec_in": 307,
        "c_out": 307,
        "freq": "h",
        "total_rows": 16992,
        "seq_len": 96,
        "label_len": 48,
    },
    "PEMS07": {
        "data": "PEMS",
        "root_path": "./data/PEMS/",
        "data_path": "PEMS07.npz",
        "enc_in": 883,
        "dec_in": 883,
        "c_out": 883,
        "freq": "h",
        "total_rows": 28224,
        "seq_len": 96,
        "label_len": 48,
    },
    "PEMS08": {
        "data": "PEMS",
        "root_path": "./data/PEMS/",
        "data_path": "PEMS08.npz",
        "enc_in": 170,
        "dec_in": 170,
        "c_out": 170,
        "freq": "h",
        "total_rows": 17856,
        "seq_len": 96,
        "label_len": 48,
    },
    "illness": {
        "data": "custom",
        "root_path": "./data/illness/",
        "data_path": "national_illness.csv",
        "enc_in": 7,
        "dec_in": 7,
        "c_out": 7,
        "freq": "w",
        "total_rows": 966,
        "seq_len": 36,
        "label_len": 18,
    },
}


def get_dataset_config(dataset_name: str) -> dict:
    if dataset_name not in DATASET_CONFIGS:
        raise ValueError(
            f"Unknown Dataset: {dataset_name}。"
            f"Supported Dataset: {list(DATASET_CONFIGS.keys())}"
        )
    return DATASET_CONFIGS[dataset_name].copy()
